import type { Metadata } from "next";
import { Figtree } from "next/font/google"; // changed to Figtree
import "./globals.css";

// Load Figtree font
const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree", // optional for CSS variable usage
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
